### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [alexpasmantier/grip-grab#5]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install`, will get the LTO-optimized version "automatically". E.g., check the `ripgrep` [profile](https://github.com/BurntSushi/ripgrep/blob/master/Cargo.toml#L76).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

Thank you.

P.S. It's more like an improvement idea rather than a bug. I created the issue just because the Discussions are disabled for the repo for now.

**Comment by alexpasmantier** [comment]
Hi, thanks for pointing that out. 

Just added LTO (fat) to the release profile which made the `gg` binary drop from **3.8 MB** to **2.3 MB** which is indeed a nice optimization. 

Also the penalty cost on build time isn't really noticeable for a small project like `gg` so that's reducing the binary size by nearly 40% almost for free.

Thanks for the tip 🙌🏻
